version: '3'
services:
  bot:
    container_name: 'telegram-check-bot'
    build:
      context: ./bot
      dockerfile: bot.Dockerfile
  filewatcher:
    container_name: 'filewatcher-helper-bot'
    restart: 'no'
    stdin_open: true
    tty: true
    build:
      context: ./filewatcher
      dockerfile: filewatcher.Dockerfile
    volumes:
      - ./filewatcher/files:/filewatcher/files